name: Build RTR-NetztestCLI-win32 (without testing)

on: [push]

jobs:
  build-win:

    runs-on: windows-lastest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history and tags
    - name: set up JDK 1.21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Gradle
      run: |
        dir
        .\gradlew.bat build --info --stacktrace :RMBTClient:shadowJar -x test
    - name: Build jpackage
      run: |
        copy RMBTClient\icon\rtr-netztest.ico RMBTClient\build
        cd RMBTClient\build\
        dir *
        $latestTag = (git describe --tags --abbrev=0).Trim()
        # jpackage fails on "v1.2.3", thus only "1.2.3"
        $latestTag = $latestTag -replace 'v', ''
        Write-Host "Using $latestTag"
        jpackage --input libs/ --name "RTR-Netztest" --icon rtr-netztest.ico --main-jar RMBTClient-all.jar  --main-class at.rtr.rmbt.client.RMBTClientRunner --type app-image --app-version "$latestTag"  --vendor "RTR" --verbose --arguments --log --description "RTR-Netztest - RMBTClient engine"
        dir *
        Compress-Archive -Path RTR-Netztest -DestinationPath RTR-NetztestCLI-win32.zip 
    - name: Archive files
      uses: actions/upload-artifact@v4
      with:
        name: RTR-NetztestCLI-win32
        path: |
          RMBTClient/build/RTR-Netztest/*
        retention-days: 90
    - name: Archive jar
      uses: actions/upload-artifact@v4
      with:
        name: RTR-NetztestCLI-jar
        path: |
          RMBTClient/build/libs/*-all.jar
        retention-days: 90
    - name: Intermediate file check
      run: |
        cd RMBTClient\build
        dir
    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: 
          D:\a\open-rmbt\open-rmbt\RMBTClient\build\RTR-NetztestCLI-win32.zip
