name: Build RTR-NetztestCLI-macos (without testing)

on: [push]

jobs:
  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history and tags
    - name: set up JDK 1.21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
    - name: Build with Gradle
      run: |
        ./gradlew :RMBTClient:shadowJar -x test
    - name: Archive files
      uses: actions/upload-artifact@v4
      with:
        name: RTR-NetztestCLI-jar
        path: |
          RMBTClient/build/libs/*-all.jar
        retention-days: 90
    - name: Build jpackage
      run: |
        cp RMBTClient/icon/rtr-netztest.icns RMBTClient/build
        cd RMBTClient/build/
        ls *
        pwd
        # Get the initial commit hash
        INITIAL_COMMIT=$(git rev-list --max-parents=0 HEAD)
        # Count commits since the initial commit
        version_tag=$(git rev-list --count ${INITIAL_COMMIT}..HEAD)
        jpackage --input libs --name "RTR-Netztest" --icon rtr-netztest.icns --main-jar RMBTClient-all.jar  --main-class at.rtr.rmbt.client.RMBTClientRunner --type app-image --app-version "$version_tag"  --vendor "RTR" --verbose --arguments --log  --description "RTR-Netztest - RMBTClient engine"
        ls *
        zip -r RTR-NetztestCLI-macos.zip RTR-Netztest.app
    - name: Archive files
      uses: actions/upload-artifact@v4
      with:
        name: RTR-NetztestCLI-macos
        path: |
          RMBTClient/build/RTR-Netztest.app/*
        retention-days: 90
    - name: Intermediate file check
      run: |
        cd RMBTClient/build/
        ls -l *
    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: 
          RMBTClient/build/RTR-NetztestCLI-macos.zip
